name: Render User Manual

on:
  push

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-latex-extra texlive-fonts-extra texlive-lang-english lmodern texlive-latex-recommended pandoc

    # Note: this is adapted from https://github.com/LibreSolar/md-manual-template/blob/master/.travis.yml
    - name: Generate manual
      shell: bash
      run: |
          pandoc -v
          cd manual
          make dist
